on:
  push:
    branches: [main]
  workflow_dispatch:

name: Debug

jobs:
  debug:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      matrix:
        config:
          - {os: macOS-latest,  r: 'release', http-user-agent: 'release'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: true

    steps:

      - uses: actions/checkout@HEAD

      - name: install pandoc devel
        uses: cderv/actions/setup-pandoc-nightly@nightly-pandoc

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@HEAD

      - uses: r-lib/actions/setup-r@HEAD
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true
