on:
  push:
    branches: [main]
  workflow_dispatch:

name: Debug

jobs:
  debug:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      matrix:
        config:
          - {os: ubuntu-latest,  r: 'devel', http-user-agent: 'release'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: true

    steps:

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@HEAD
