on:
  workflow_dispatch:

name: Test TinyTeX installers on Windows

jobs:
  debug:
    runs-on: windows-latest

    steps:

      - name: Install 2026.03.02 via .zip
        uses: r-lib/actions/setup-tinytex@HEAD
        env:
          TINYTEX_VERSION: '2026.03.02'

      - name: Install 2026.04 via .exe
        uses: r-lib/actions/setup-tinytex@HEAD
        env:
          TINYTEX_VERSION: '2026.04'

      - name: Install current daily via .exe
        uses: r-lib/actions/setup-tinytex@HEAD
